modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/pau101/Fairy-Lights/issues"
license="MIT"
[[mods]]
	modId="fairylights"
	version="5.0.0"
	displayName="Fairy Lights"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/fairy-lights"
	authors="pau101"
	description="Fairy Lights introduces decorative string lights, bunting, garland, and more!"
	logoFile="logo.png"
[[dependencies.fairylights]]
	modId="forge"
	mandatory=true
	versionRange="[40,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.fairylights]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.2,1.19)"
	ordering="NONE"
	side="BOTH"
